// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBb2oaNMjpukjNkH1xzjKHaZAIWuMgLZI',
    appId: '1:921159155125:web:09781f594613f0b5c5edfc',
    messagingSenderId: '921159155125',
    projectId: 'demoapp-134a9',
    authDomain: 'demoapp-134a9.firebaseapp.com',
    storageBucket: 'demoapp-134a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvvwYBUgxvE_wHFli2nVcSxFizBCxY8rg',
    appId: '1:921159155125:android:52c6fd00b27d3f1ac5edfc',
    messagingSenderId: '921159155125',
    projectId: 'demoapp-134a9',
    storageBucket: 'demoapp-134a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDThVxUqXDk4K4m0Rg1cjGwKlFnIg2DMd8',
    appId: '1:921159155125:ios:2faece1911096314c5edfc',
    messagingSenderId: '921159155125',
    projectId: 'demoapp-134a9',
    storageBucket: 'demoapp-134a9.appspot.com',
    iosBundleId: 'com.example.crudtest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBb2oaNMjpukjNkH1xzjKHaZAIWuMgLZI',
    appId: '1:921159155125:web:3c450a730c54f95cc5edfc',
    messagingSenderId: '921159155125',
    projectId: 'demoapp-134a9',
    authDomain: 'demoapp-134a9.firebaseapp.com',
    storageBucket: 'demoapp-134a9.appspot.com',
  );
}
